create database python_workbench;
use python_workbench;
create table student(rollno int, name varchar(20), location varchar(30), phone int, email varchar(30));
insert into student(rollno,name,location,phone,email) values(102,'Roshan','Kollam','7563232520','roshan23@yopmail.com');
select name,location from student where rollno=102;
create table country(cid int, name varchar(30));
insert into country(cid, name) values(6, 'India');
select distinct name from country;
select * from student where address like 'k%';
select * from student where rollno > 100 and rollno != 102;
select * from student where rollno between 100 and 105;
select * from student where address in ('kochi','kollam');
select * from student order by name;
select * from student order by name desc;
select count(rollno) from student;
alter table student add house_address varchar(30);
alter table student drop house_address;
alter table student rename column location to address;
alter table student modify column address varchar(50);
alter table student drop email;
create table products(pid varchar(20), pname varchar(30), unit double, price double);
insert into products(pid,pname,unit,price) values('prd003','Kyma Rice',2.0,400.0);
select count(pid) from products where price > 300;
select count(*) as no_of_products from products;
select sum(price) as Sum_of_products from products where price > 300;
select avg(price) as Avg_of_products from products where price > 300;
select * from products where price > (select avg(price) from products);
select pid, pname from products where price > (select avg(price) from products) group by pid,pname;
insert into products(pid,pname,unit,price) values('prd004','Milma Ghee',null,180.0);
select *from products where unit is not null;
create table person(pid int not null unique, name varchar(20), address varchar(50), mobno varchar(20), email varchar(30));
insert into person(pid,name,address,mobno,email,id) values(5,'Jain','Kochi','9860000000','jain7@yopmail.com',101);
alter table person add column id varchar(20);
alter table person add constraint unique(id);
alter table person drop column id;
alter table person add column id varchar(20);
alter table person add constraint uc_person1 unique(id);
alter table person drop index uc_person1;
drop table person;
create table person(pid int NOT NULL,pname varchar(20), location varchar(20),mobno varchar(20),email varchar(30),unique(mobno,email));
alter table person modify pid int unique;
insert into person(pid,pname,location,mobno,email) values(2,'David','Kochi','7645000000','ashish24@yopmail.com');
alter table person add column employment_status varchar(20);
alter table person add column retire_date varchar(20);
alter table person add constraint EMP_STATUS unique(retire_date,employment_status);
select * from person;
alter table person add primary key(pid);
create table accoutant(accid int primary key,accname varchar(20), mobno varchar(20), email varchar(30), unique(mobno,email));
alter table accoutant add constraint ACC_STATUS primary key(mobno);
create table animal(no int, name varchar(20));
alter table animal add constraint an_tk primary key(no,name);
alter table animal drop primary key;
alter table accoutant add column pid int;
alter table products add constraint primary key(pid);
create table orders(order_id int not null, pid varchar(20) not null, primary key(order_id),foreign key(pid) references products(pid));
SHOW CREATE TABLE products;
alter table orders add column accid int not null;
alter table orders add constraint emp_orders foreign key(accid) references accoutant(accid);
alter table orders drop foreign key emp_orders;
alter table animal add primary key(no);
alter table animal drop primary key;
create table order_history(hid int primary key, pid varchar(20) references pid(products),order_id int references order_id(orders));
select * from products;
update products set unit=1.0 where pid='prd004';
insert into products(pid,pname,unit,price) values('prd005','Kayam',1.0,50.0);
delete from products where pid='prd005';
select * from products where price between 40 and 50;
select * from products where pname in ('Lux Soap','Kyma Rice');
select * from products where pname like 'a%';
select * from products where pname like '%e';
select * from products where pname like '__x%';
select * from products where pname like '_u%';
select * from products where pname like '%__ee';
select * from products where pname like '_y%';
select * from products where pname like '%i__';
select * from products where pname like 'a%' or price=400;
select * from products where pname like 'a%' and price=400;
select * from products where pname like '%ce%';
select * from products where pname not like '%ma%';
create table members(id int not null, name varchar(20), age int);
insert into members(id,name) values(2,'ask');

select * from products;

#pending topics
#views


